using System;
using System.Collections.Generic;
using Vintagestory.API.Common;

namespace WildFarming.Ecosystem
{
    /// <summary>
    /// Wildcraft Fruit <c>fruitvine</c> / <c>bottomfruitvine</c> / <c>bottomtreevine</c> blocks.
    /// Climate-only ecology (spread disabled); growth stays in Herbarium BE.
    /// Generated by community/tools/generate_wildcraftfruit_fruitvine_table.py
    /// </summary>
    internal static class WildcraftFruitFruitingVineEcology
    {
        internal readonly struct Profile
        {
            public readonly float MinTemp, MaxTemp, MinRain, MaxRain, MinForest, MaxForest;
            public readonly bool OnTrees;

            public Profile(float minTemp, float maxTemp, float minRain, float maxRain, float minForest, float maxForest, bool onTrees)
            {
                MinTemp = minTemp; MaxTemp = maxTemp; MinRain = minRain; MaxRain = maxRain;
                MinForest = minForest; MaxForest = maxForest; OnTrees = onTrees;
            }
        }

        static readonly Dictionary<string, Profile> ByType =
            new Dictionary<string, Profile>(StringComparer.OrdinalIgnoreCase)
            {
                ["blackgrape"] = new Profile(16.0f, 30.0f, 0.3f, 1.0f, 0.3f, 1.0f, false),
                ["bryony"] = new Profile(0.0f, 14.0f, 0.3f, 1.0f, 0.3f, 1.0f, false),
                ["cucumber"] = new Profile(8.0f, 26.0f, 0.4f, 1.0f, 0.2f, 1.0f, false),
                ["foxgrape"] = new Profile(10.0f, 28.0f, 0.4f, 1.0f, 0.3f, 1.0f, false),
                ["granadilla"] = new Profile(23.0f, 40.0f, 0.65f, 1.0f, 0.3f, 1.0f, false),
                ["hairyappleberry"] = new Profile(22.0f, 36.0f, 0.65f, 1.0f, 0.3f, 1.0f, false),
                ["ivy"] = new Profile(-8.0f, 24.0f, 0.2f, 1.0f, 0.5f, 1.0f, false),
                ["kiwi"] = new Profile(18.0f, 30.0f, 0.5f, 1.0f, 0.3f, 1.0f, false),
                ["kolomikta"] = new Profile(6.0f, 18.0f, 0.5f, 1.0f, 0.3f, 1.0f, false),
                ["passionfruit"] = new Profile(21.0f, 40.0f, 0.65f, 1.0f, 0.3f, 1.0f, false),
                ["purpleappleberry"] = new Profile(20.0f, 30.0f, 0.5f, 1.0f, 0.3f, 1.0f, false),
                ["redgrape"] = new Profile(2.0f, 34.0f, 0.35f, 1.0f, 0.0f, 1.0f, true),
                ["virgingrape"] = new Profile(6.0f, 26.0f, 0.3f, 1.0f, 0.3f, 1.0f, false),
                ["whitegrape"] = new Profile(4.0f, 36.0f, 0.35f, 1.0f, 0.0f, 1.0f, true),
                ["woodbine"] = new Profile(4.0f, 18.0f, 0.5f, 1.0f, 0.3f, 1.0f, false),
            };

        static readonly string[] BlockPrefixes =
        {
            "fruitvine-",
            "bottomfruitvine-",
            "bottomtreevine-",
        };

        public static bool IsFruitingVineBlock(Block block) => TryGetVineType(block, out _);

        public static bool TryGetVineType(Block block, out string vineType)
        {
            vineType = null;
            if (block?.Code == null || block.Code.Domain != "wildcraftfruit") return false;
            string path = block.Code.Path;
            if (string.IsNullOrEmpty(path)) return false;

            for (int i = 0; i < BlockPrefixes.Length; i++)
            {
                string prefix = BlockPrefixes[i];
                if (!path.StartsWith(prefix, StringComparison.Ordinal)) continue;
                string rest = path.Substring(prefix.Length);
                int dash = rest.IndexOf('-');
                if (dash <= 0) return false;
                vineType = rest.Substring(0, dash);
                return !string.IsNullOrEmpty(vineType);
            }

            return false;
        }

        public static bool TryGetProfile(string vineType, out Profile profile)
        {
            profile = default;
            if (string.IsNullOrEmpty(vineType)) return false;
            return ByType.TryGetValue(vineType, out profile);
        }

        public static bool TryGetSpreadBlock(Block block, out AssetLocation spreadBlock)
        {
            spreadBlock = null;
            if (!TryGetVineType(block, out string vineType)) return false;
            string path = block.Code.Path;
            if (path.StartsWith("bottomtreevine-", StringComparison.Ordinal)
                || path.StartsWith("bottomfruitvine-", StringComparison.Ordinal))
            {
                spreadBlock = new AssetLocation("wildcraftfruit", "fruitvine-" + vineType + "-empty-north");
                return true;
            }

            if (path.StartsWith("fruitvine-", StringComparison.Ordinal))
            {
                int lastDash = path.LastIndexOf('-');
                if (lastDash <= 0) return false;
                string side = path.Substring(lastDash + 1);
                spreadBlock = new AssetLocation("wildcraftfruit", "fruitvine-" + vineType + "-empty-" + side);
                return true;
            }

            return false;
        }
    }
}
