using System;
using System.Collections.Generic;

namespace WildFarming.Ecosystem
{
    internal static class WildcraftFruitWorldgenPlants
    {
        internal readonly struct Entry
        {
            public readonly float MinTemp, MaxTemp, MinRain, MaxRain, MinForest, MaxForest, SpreadRate;
            public readonly EcologyHabitat Habitat;
            public readonly string SourceFile;

            public Entry(float minTemp, float maxTemp, float minRain, float maxRain, float minForest, float maxForest, EcologyHabitat habitat, float spreadRate, string sourceFile)
            {
                MinTemp = minTemp; MaxTemp = maxTemp; MinRain = minRain; MaxRain = maxRain; MinForest = minForest; MaxForest = maxForest;
                Habitat = habitat; SpreadRate = spreadRate; SourceFile = sourceFile;
            }
        }

        static readonly Dictionary<string, Entry> ByBlockCode =
            new Dictionary<string, Entry>(StringComparer.Ordinal)
            {
                ["wildcraftfruit:berrybush-ballart-empty"] = new Entry(14.0f, 20.0f, 0.2f, 0.6f, 0.1f, 0.5f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-ballart-flowering"] = new Entry(14.0f, 20.0f, 0.2f, 0.6f, 0.1f, 0.5f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-ballart-ripe"] = new Entry(14.0f, 20.0f, 0.2f, 0.6f, 0.1f, 0.5f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-blackcurrant-empty"] = new Entry(4.0f, 16.0f, 0.5f, 1.0f, 0.3f, 1.0f, EcologyHabitat.Terrestrial, 0.364f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-blackcurrant-flowering"] = new Entry(4.0f, 16.0f, 0.5f, 1.0f, 0.3f, 1.0f, EcologyHabitat.Terrestrial, 0.364f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-blackcurrant-ripe"] = new Entry(4.0f, 16.0f, 0.5f, 1.0f, 0.3f, 1.0f, EcologyHabitat.Terrestrial, 0.364f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-bladdernut-empty"] = new Entry(12.0f, 18.0f, 0.5f, 0.8f, 0.3f, 0.7f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-bladdernut-flowering"] = new Entry(12.0f, 18.0f, 0.5f, 0.8f, 0.3f, 0.7f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-bladdernut-ripe"] = new Entry(12.0f, 18.0f, 0.5f, 0.8f, 0.3f, 0.7f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-clementine-empty"] = new Entry(20.0f, 30.0f, 0.5f, 0.9f, 0.5f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-clementine-flowering"] = new Entry(20.0f, 30.0f, 0.5f, 0.9f, 0.5f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-clementine-ripe"] = new Entry(20.0f, 30.0f, 0.5f, 0.9f, 0.5f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-dwarfpine-empty"] = new Entry(-20.0f, 2.0f, 0.3f, 0.8f, 0.0f, 0.6f, EcologyHabitat.Terrestrial, 0.351f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-dwarfpine-flowering"] = new Entry(-20.0f, 2.0f, 0.3f, 0.8f, 0.0f, 0.6f, EcologyHabitat.Terrestrial, 0.351f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-dwarfpine-ripe"] = new Entry(-20.0f, 2.0f, 0.3f, 0.8f, 0.0f, 0.6f, EcologyHabitat.Terrestrial, 0.351f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-hazel-empty"] = new Entry(-6.0f, 12.0f, 0.4f, 0.8f, 0.7f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-hazel-flowering"] = new Entry(-6.0f, 12.0f, 0.4f, 0.8f, 0.7f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-hazel-ripe"] = new Entry(-6.0f, 12.0f, 0.4f, 0.8f, 0.7f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-honeysuckle-empty"] = new Entry(-8.0f, 10.0f, 0.6f, 1.0f, 0.0f, 0.4f, EcologyHabitat.ReedNearWater, 0.462f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-honeysuckle-flowering"] = new Entry(-8.0f, 10.0f, 0.6f, 1.0f, 0.0f, 0.4f, EcologyHabitat.ReedNearWater, 0.462f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-honeysuckle-ripe"] = new Entry(-8.0f, 10.0f, 0.6f, 1.0f, 0.0f, 0.4f, EcologyHabitat.ReedNearWater, 0.462f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-huckleberry-empty"] = new Entry(-6.0f, 16.0f, 0.3f, 1.0f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.361f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-huckleberry-flowering"] = new Entry(-6.0f, 16.0f, 0.3f, 1.0f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.361f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-huckleberry-ripe"] = new Entry(-6.0f, 16.0f, 0.3f, 1.0f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.361f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-josta-empty"] = new Entry(4.0f, 16.0f, 0.3f, 0.8f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-josta-flowering"] = new Entry(4.0f, 16.0f, 0.3f, 0.8f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-josta-ripe"] = new Entry(4.0f, 16.0f, 0.3f, 0.8f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-juniper-empty"] = new Entry(-15.0f, 6.0f, 0.4f, 0.9f, 0.0f, 0.4f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-juniper-flowering"] = new Entry(-15.0f, 6.0f, 0.4f, 0.9f, 0.0f, 0.4f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-juniper-ripe"] = new Entry(-15.0f, 6.0f, 0.4f, 0.9f, 0.0f, 0.4f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-lillypillyblue-empty"] = new Entry(27.0f, 48.0f, 0.75f, 1.0f, 0.65f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-lillypillyblue-flowering"] = new Entry(27.0f, 48.0f, 0.75f, 1.0f, 0.65f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-lillypillyblue-ripe"] = new Entry(27.0f, 48.0f, 0.75f, 1.0f, 0.65f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-lillypillypink-empty"] = new Entry(27.0f, 46.0f, 0.6f, 0.9f, 0.5f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-lillypillypink-flowering"] = new Entry(27.0f, 46.0f, 0.6f, 0.9f, 0.5f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-lillypillypink-ripe"] = new Entry(27.0f, 46.0f, 0.6f, 0.9f, 0.5f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-lillypillywhite-empty"] = new Entry(19.0f, 25.0f, 0.7f, 1.0f, 0.65f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-lillypillywhite-flowering"] = new Entry(19.0f, 25.0f, 0.7f, 1.0f, 0.65f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-lillypillywhite-ripe"] = new Entry(19.0f, 25.0f, 0.7f, 1.0f, 0.65f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-marita-empty"] = new Entry(18.0f, 40.0f, 0.6f, 1.0f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.49f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-marita-flowering"] = new Entry(18.0f, 40.0f, 0.6f, 1.0f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.49f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-marita-ripe"] = new Entry(18.0f, 40.0f, 0.6f, 1.0f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.49f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-midyimberry-empty"] = new Entry(22.0f, 44.0f, 0.5f, 0.9f, 0.0f, 0.7f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-midyimberry-flowering"] = new Entry(22.0f, 44.0f, 0.5f, 0.9f, 0.0f, 0.7f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-midyimberry-ripe"] = new Entry(22.0f, 44.0f, 0.5f, 0.9f, 0.0f, 0.7f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-mingimingi-empty"] = new Entry(16.0f, 28.0f, 0.6f, 1.0f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.357f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-mingimingi-flowering"] = new Entry(16.0f, 28.0f, 0.6f, 1.0f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.357f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-mingimingi-ripe"] = new Entry(16.0f, 28.0f, 0.6f, 1.0f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.357f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-pilo-empty"] = new Entry(16.0f, 28.0f, 0.3f, 0.8f, 0.0f, 0.3f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-pilo-flowering"] = new Entry(16.0f, 28.0f, 0.3f, 0.8f, 0.0f, 0.3f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-pilo-ripe"] = new Entry(16.0f, 28.0f, 0.3f, 0.8f, 0.0f, 0.3f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-pistachio-empty"] = new Entry(24.0f, 40.0f, 0.25f, 0.5f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.364f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-pistachio-flowering"] = new Entry(24.0f, 40.0f, 0.25f, 0.5f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.364f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-pistachio-ripe"] = new Entry(24.0f, 40.0f, 0.25f, 0.5f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.364f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-redcurrant-empty"] = new Entry(-5.0f, 16.0f, 0.5f, 1.0f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-redcurrant-flowering"] = new Entry(-5.0f, 16.0f, 0.5f, 1.0f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-redcurrant-ripe"] = new Entry(0.0f, 20.0f, 0.5f, 1.0f, 0.5f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-seamango-empty"] = new Entry(26.0f, 40.0f, 0.65f, 1.0f, 0.6f, 1.0f, EcologyHabitat.ReedNearWater, 0.574f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-seamango-flowering"] = new Entry(26.0f, 40.0f, 0.65f, 1.0f, 0.6f, 1.0f, EcologyHabitat.ReedNearWater, 0.574f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-seamango-ripe"] = new Entry(26.0f, 40.0f, 0.65f, 1.0f, 0.6f, 1.0f, EcologyHabitat.ReedNearWater, 0.574f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-snowberry-empty"] = new Entry(0.0f, 16.0f, 0.5f, 0.8f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-snowberry-flowering"] = new Entry(0.0f, 16.0f, 0.5f, 0.8f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-snowberry-ripe"] = new Entry(0.0f, 16.0f, 0.5f, 0.8f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-sumac-empty"] = new Entry(12.0f, 40.0f, 0.1f, 0.4f, 0.0f, 0.4f, EcologyHabitat.ReedNearWater, 0.63f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-sumac-flowering"] = new Entry(12.0f, 40.0f, 0.1f, 0.4f, 0.0f, 0.4f, EcologyHabitat.ReedNearWater, 0.63f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-sumac-ripe"] = new Entry(12.0f, 40.0f, 0.1f, 0.4f, 0.0f, 0.4f, EcologyHabitat.ReedNearWater, 0.63f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-swamphuckle-empty"] = new Entry(6.0f, 18.0f, 0.6f, 1.0f, 0.0f, 0.6f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-swamphuckle-flowering"] = new Entry(6.0f, 18.0f, 0.6f, 1.0f, 0.0f, 0.6f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-swamphuckle-ripe"] = new Entry(6.0f, 18.0f, 0.6f, 1.0f, 0.0f, 0.6f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-whitecurrant-empty"] = new Entry(0.0f, 20.0f, 0.5f, 1.0f, 0.5f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:berrybush-whitecurrant-flowering"] = new Entry(0.0f, 20.0f, 0.5f, 1.0f, 0.5f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:cactus-barrelcactus-empty"] = new Entry(22.0f, 50.0f, 0.0f, 0.25f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.403f, "game:worldgen/blockpatches/other.json"),
                ["wildcraftfruit:cactus-barrelcactus-flowering"] = new Entry(22.0f, 50.0f, 0.0f, 0.25f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.403f, "game:worldgen/blockpatches/other.json"),
                ["wildcraftfruit:cactus-topsaguaro-empty"] = new Entry(22.0f, 50.0f, 0.0f, 0.25f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/other.json"),
                ["wildcraftfruit:cactus-topsaguaro-flowering"] = new Entry(22.0f, 50.0f, 0.0f, 0.25f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/other.json"),
                ["wildcraftfruit:cactus-topsaguaro-ripe"] = new Entry(22.0f, 50.0f, 0.0f, 0.25f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/other.json"),
                ["wildcraftfruit:cactus-youngsaguaro-empty"] = new Entry(22.0f, 50.0f, 0.0f, 0.25f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/other.json"),
                ["wildcraftfruit:cactus-youngsaguaro-flowering"] = new Entry(22.0f, 50.0f, 0.0f, 0.25f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/other.json"),
                ["wildcraftfruit:cactus-youngsaguaro-ripe"] = new Entry(22.0f, 50.0f, 0.0f, 0.25f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/other.json"),
                ["wildcraftfruit:groundberryplant-cheeseberry-empty"] = new Entry(24.0f, 46.0f, 0.5f, 0.9f, 0.4f, 0.9f, EcologyHabitat.Terrestrial, 0.462f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:groundberryplant-cheeseberry-flowering"] = new Entry(24.0f, 46.0f, 0.5f, 0.9f, 0.4f, 0.9f, EcologyHabitat.Terrestrial, 0.462f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:groundberryplant-cheeseberry-ripe"] = new Entry(24.0f, 46.0f, 0.5f, 0.9f, 0.4f, 0.9f, EcologyHabitat.Terrestrial, 0.462f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:groundberryplant-cranberry-empty"] = new Entry(-10.0f, 12.0f, 0.6f, 1.0f, 0.0f, 0.3f, EcologyHabitat.Terrestrial, 0.42f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:groundberryplant-cranberry-flowering"] = new Entry(-10.0f, 12.0f, 0.6f, 1.0f, 0.0f, 0.3f, EcologyHabitat.Terrestrial, 0.42f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:groundberryplant-cranberry-ripe"] = new Entry(-10.0f, 12.0f, 0.6f, 1.0f, 0.0f, 0.3f, EcologyHabitat.Terrestrial, 0.42f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:groundberryplant-kakaha-empty"] = new Entry(16.0f, 26.0f, 0.6f, 1.0f, 0.3f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:groundberryplant-kakaha-flowering"] = new Entry(16.0f, 26.0f, 0.6f, 1.0f, 0.3f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:groundberryplant-kakaha-ripe"] = new Entry(16.0f, 26.0f, 0.6f, 1.0f, 0.3f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-beachrose-empty"] = new Entry(12.0f, 24.0f, 0.4f, 0.8f, 0.0f, 0.4f, EcologyHabitat.Terrestrial, 0.357f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-beachrose-flowering"] = new Entry(12.0f, 24.0f, 0.4f, 0.8f, 0.0f, 0.4f, EcologyHabitat.Terrestrial, 0.357f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-beachrose-ripe"] = new Entry(12.0f, 24.0f, 0.4f, 0.8f, 0.0f, 0.4f, EcologyHabitat.Terrestrial, 0.357f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-blossomquince-empty"] = new Entry(4.0f, 14.0f, 0.4f, 0.8f, 0.2f, 0.6f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-blossomquince-flowering"] = new Entry(4.0f, 14.0f, 0.4f, 0.8f, 0.2f, 0.6f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-blossomquince-ripe"] = new Entry(4.0f, 14.0f, 0.4f, 0.8f, 0.2f, 0.6f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-deserthackberry-empty"] = new Entry(12.0f, 40.0f, 0.0f, 0.3f, 0.0f, 0.2f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-deserthackberry-flowering"] = new Entry(12.0f, 40.0f, 0.0f, 0.3f, 0.0f, 0.2f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-deserthackberry-ripe"] = new Entry(12.0f, 40.0f, 0.0f, 0.3f, 0.0f, 0.2f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-desertlime-empty"] = new Entry(26.0f, 44.0f, 0.1f, 0.4f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.371f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-desertlime-flowering"] = new Entry(26.0f, 44.0f, 0.1f, 0.4f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.371f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-desertlime-ripe"] = new Entry(26.0f, 44.0f, 0.1f, 0.4f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.371f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-dogrose-empty"] = new Entry(-10.0f, 8.0f, 0.3f, 0.8f, 0.0f, 0.45f, EcologyHabitat.Terrestrial, 0.42f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-dogrose-flowering"] = new Entry(-10.0f, 8.0f, 0.3f, 0.8f, 0.0f, 0.45f, EcologyHabitat.Terrestrial, 0.42f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-dogrose-ripe"] = new Entry(-10.0f, 8.0f, 0.3f, 0.8f, 0.0f, 0.45f, EcologyHabitat.Terrestrial, 0.42f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-gooseberry-empty"] = new Entry(4.0f, 16.0f, 0.3f, 0.8f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-gooseberry-flowering"] = new Entry(4.0f, 16.0f, 0.3f, 0.8f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-gooseberry-ripe"] = new Entry(4.0f, 16.0f, 0.3f, 0.8f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-shangjuan-empty"] = new Entry(18.0f, 30.0f, 0.4f, 0.8f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-shangjuan-flowering"] = new Entry(18.0f, 30.0f, 0.4f, 0.8f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-shangjuan-ripe"] = new Entry(18.0f, 30.0f, 0.4f, 0.8f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-sloe-empty"] = new Entry(2.0f, 16.0f, 0.5f, 0.9f, 0.3f, 0.8f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-sloe-flowering"] = new Entry(2.0f, 16.0f, 0.5f, 0.9f, 0.3f, 0.8f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-sloe-ripe"] = new Entry(2.0f, 16.0f, 0.5f, 0.9f, 0.3f, 0.8f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-trifoliate-empty"] = new Entry(16.0f, 21.0f, 0.4f, 0.8f, 0.5f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-trifoliate-flowering"] = new Entry(16.0f, 21.0f, 0.4f, 0.8f, 0.5f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-trifoliate-ripe"] = new Entry(16.0f, 21.0f, 0.4f, 0.8f, 0.5f, 1.0f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-yuzu-empty"] = new Entry(18.0f, 23.0f, 0.5f, 0.9f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-yuzu-flowering"] = new Entry(18.0f, 23.0f, 0.5f, 0.9f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyberrybush-yuzu-ripe"] = new Entry(18.0f, 23.0f, 0.5f, 0.9f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyshortbush-caper-empty"] = new Entry(18.0f, 28.0f, 0.2f, 0.7f, 0.2f, 0.5f, EcologyHabitat.Terrestrial, 0.364f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyshortbush-caper-flowering"] = new Entry(18.0f, 28.0f, 0.2f, 0.7f, 0.2f, 0.5f, EcologyHabitat.Terrestrial, 0.364f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyshortbush-caper-ripe"] = new Entry(18.0f, 28.0f, 0.2f, 0.7f, 0.2f, 0.5f, EcologyHabitat.Terrestrial, 0.364f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyshortbush-dewberry-empty"] = new Entry(4.0f, 12.0f, 0.5f, 1.0f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyshortbush-dewberry-flowering"] = new Entry(4.0f, 12.0f, 0.5f, 1.0f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:pricklyshortbush-dewberry-ripe"] = new Entry(4.0f, 12.0f, 0.5f, 1.0f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-bearberry-empty"] = new Entry(-10.0f, 10.0f, 0.25f, 0.55f, 0.0f, 0.6f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-bearberry-flowering"] = new Entry(-10.0f, 10.0f, 0.25f, 0.55f, 0.0f, 0.6f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-bearberry-ripe"] = new Entry(-10.0f, 10.0f, 0.25f, 0.55f, 0.0f, 0.6f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-bilberry-empty"] = new Entry(8.0f, 18.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-bilberry-flowering"] = new Entry(8.0f, 18.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-bilberry-ripe"] = new Entry(8.0f, 18.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.406f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-blueberry-empty"] = new Entry(-10.0f, 10.0f, 0.6f, 1.0f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-blueberry-flowering"] = new Entry(-10.0f, 10.0f, 0.6f, 1.0f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-blueberry-ripe"] = new Entry(-10.0f, 10.0f, 0.6f, 1.0f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-bluetongue-empty"] = new Entry(24.0f, 44.0f, 0.6f, 1.0f, 0.2f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-bluetongue-flowering"] = new Entry(24.0f, 44.0f, 0.6f, 1.0f, 0.2f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-bluetongue-ripe"] = new Entry(24.0f, 44.0f, 0.6f, 1.0f, 0.2f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-flaxlily-empty"] = new Entry(27.0f, 40.0f, 0.6f, 0.9f, 0.3f, 0.9f, EcologyHabitat.Terrestrial, 0.434f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-flaxlily-flowering"] = new Entry(27.0f, 40.0f, 0.6f, 0.9f, 0.3f, 0.9f, EcologyHabitat.Terrestrial, 0.434f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-flaxlily-ripe"] = new Entry(27.0f, 40.0f, 0.6f, 0.9f, 0.3f, 0.9f, EcologyHabitat.Terrestrial, 0.434f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-munthari-empty"] = new Entry(26.0f, 44.0f, 0.3f, 0.7f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.371f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-munthari-flowering"] = new Entry(26.0f, 44.0f, 0.3f, 0.7f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.371f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shortberrybush-munthari-ripe"] = new Entry(26.0f, 44.0f, 0.3f, 0.7f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.371f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-greenbellpepper-empty"] = new Entry(18.0f, 26.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.385f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-greenbellpepper-flowering"] = new Entry(18.0f, 26.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.385f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-greenbellpepper-ripe"] = new Entry(18.0f, 26.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.385f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-habanero-empty"] = new Entry(20.0f, 28.0f, 0.5f, 0.7f, 0.0f, 0.3f, EcologyHabitat.Terrestrial, 0.375f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-habanero-flowering"] = new Entry(20.0f, 28.0f, 0.5f, 0.7f, 0.0f, 0.3f, EcologyHabitat.Terrestrial, 0.375f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-habanero-ripe"] = new Entry(20.0f, 28.0f, 0.5f, 0.7f, 0.0f, 0.3f, EcologyHabitat.Terrestrial, 0.375f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-jalapeno-empty"] = new Entry(20.0f, 26.0f, 0.6f, 0.9f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-jalapeno-flowering"] = new Entry(20.0f, 26.0f, 0.6f, 0.9f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-jalapeno-ripe"] = new Entry(20.0f, 26.0f, 0.6f, 0.9f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-oldmansaltbush-empty"] = new Entry(26.0f, 44.0f, 0.1f, 0.3f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.371f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-oldmansaltbush-flowering"] = new Entry(26.0f, 44.0f, 0.1f, 0.3f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.371f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-oldmansaltbush-ripe"] = new Entry(26.0f, 44.0f, 0.1f, 0.3f, 0.0f, 1.0f, EcologyHabitat.Terrestrial, 0.371f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-orangebellpepper-empty"] = new Entry(18.0f, 26.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.385f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-orangebellpepper-flowering"] = new Entry(18.0f, 26.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.385f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-orangebellpepper-ripe"] = new Entry(18.0f, 26.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.385f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-redbellpepper-empty"] = new Entry(18.0f, 26.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.385f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-redbellpepper-flowering"] = new Entry(18.0f, 26.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.385f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-redbellpepper-ripe"] = new Entry(18.0f, 26.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.385f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-tomatillo-empty"] = new Entry(16.0f, 28.0f, 0.5f, 0.8f, 0.2f, 0.8f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-tomatillo-flowering"] = new Entry(16.0f, 28.0f, 0.5f, 0.8f, 0.2f, 0.8f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-tomatillo-ripe"] = new Entry(16.0f, 28.0f, 0.5f, 0.8f, 0.2f, 0.8f, EcologyHabitat.Terrestrial, 0.378f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-turkscap-empty"] = new Entry(20.0f, 30.0f, 0.5f, 0.8f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-turkscap-flowering"] = new Entry(20.0f, 30.0f, 0.5f, 0.8f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-turkscap-ripe"] = new Entry(20.0f, 30.0f, 0.5f, 0.8f, 0.4f, 1.0f, EcologyHabitat.Terrestrial, 0.392f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-yellowbellpepper-empty"] = new Entry(18.0f, 26.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.385f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-yellowbellpepper-flowering"] = new Entry(18.0f, 26.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.385f, "game:worldgen/blockpatches/berrybush.json"),
                ["wildcraftfruit:shrubberrybush-yellowbellpepper-ripe"] = new Entry(18.0f, 26.0f, 0.4f, 0.8f, 0.0f, 0.5f, EcologyHabitat.Terrestrial, 0.385f, "game:worldgen/blockpatches/berrybush.json"),
            };

        public static bool TryGet(string blockCode, out Entry entry)
        {
            entry = default;
            if (string.IsNullOrEmpty(blockCode)) return false;
            return ByBlockCode.TryGetValue(blockCode, out entry);
        }
    }
}
